### ISSUE TITLE
Text processing issue

### ISSUE THREAD

**Issue by gao339** [writecrow/text_processing#13]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by markfullmer** [comment]
Hi @gao339 ! I did a little Googling and I ran across the exact error you experienced on your Mac with running git: 

https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path

That comment led me to the original post at http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/ , which looks like a valid explanation of the problem and a reasonable fix.

Tomorrow, let's try running `xcode-select --install` in your terminal and see if that fixes the issue for you.

**Comment by markfullmer** [comment]
This was indeed resolved by the above method. Closing.
