### ISSUE TITLE
"charmap" problem for windows (not see in Mac during the tech training workshop)

### ISSUE THREAD

**Issue by Gee-CityU** [writecrow/text_processing#15]
File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 506: character maps to <undefined>

**Comment by markfullmer** [comment]
Looking into this this week...!

**Comment by markfullmer** [comment]
@gelan890926 , @abushner & @Velazqa , thanks for reporting this issue. I've done a bit of research and isolated it to a difference in how different operating systems handle the default character encoding formats. In short, for Python 3 on Windows, we need to specify what encoding format should be used when using the `open()` method. See http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html#files-in-an-ascii-compatible-encoding-best-effort-is-acceptable

I'll open a pull request shortly to revise a couple of our scripts so they should work fine on Windows machines.
