### ISSUE TITLE
FFLOC_Scraper needs to check that a payload isn't empty when downloading

### ISSUE THREAD

**Issue by NikKirstein** [writecrow/text_processing#4]
More of a note to self.  Currently, on the FFLOC website, download links exist for all the zip files even if there is no actual file to download.  This results in the scraper downloading a 0kb zip file which causes problems later.

The unzipper was recently updated to check for empty files and non-directories to skip them but the scraper should be more robust to simply not retrieve bad files.

**Comment by markfullmer** [comment]
Closing, as this is informational only.
